#!/bin/sh

scripts/setup_common.py --full-name="IRYU Evaluation board" \
                        --cross-compile="arm-sony-linux-gnueabi-armv7a-dev-" \
                        --arch-name="arm" \
                        --target-name="advnpf0" \
                        --fixup-kernel-headers="scripts/kernel_headers/default.fixup" \
                        --defconfig-base="arch/arm/configs/advnpf0_defconfig" \
                        --build-instruction="make" \
                        --image="arch/arm/boot/uImage" \
                        "$@"
